### ISSUE TITLE
Crawling depthwise instead of breadthwise

### ISSUE THREAD

**Issue by deepika537** [salimk/Rcrawler#12]
When I set Maxdepth=1, It is crawling depth wise instead of breadthwise.
For example, page1.html has two links(page2.html,page3.html) in it. 
Page2.html has link to page5.html

I want to crawl page1.html,page2.html,pages3.html but Rcrawler is crawling page1.html,page2.html,page5.html

Also, How can I crawl only starting page of a website with Rcrawler(just page1.html). I tried with MaxDepth=0. But it is not downloading any page content. It is just creating folder with the domain name.

**Comment by salimk** [comment]
Hello, 
Rcrawler use depthwise strategy;  we have fixed this issue. as well as for Maxdepth. you should set it to 0 if you want to crawl only the page you provide.  We have released a new version of Rcrawler 0.1.4 ,  it will be available on cran tomorrow, 

We tested it on  this demo structure http://glofile.com/folder/  
`Rcrawler(Website = "http://glofile.com/folder/", no_cores = 1, no_conn = 1 ) 
`
![example-structure](https://user-images.githubusercontent.com/17308124/31866198-d7918ade-b773-11e7-917e-a943358412dd.PNG)

Also we have added a new feature, the ability to create a network representation of the website you crawled . 
`Rcrawler(Website = "http://glofile.com/folder/", no_cores = 4, no_conn = 4 , NetworkData = TRUE)
`
Then use igraph to plot your network.
`library(igraph)
`
`bsk.network<-graph.data.frame(NetwEgdes, directed=T)
`
`plot(bsk.network)
`
 ![example-graph](https://user-images.githubusercontent.com/17308124/31866258-ec173c50-b774-11e7-86f2-03051298039d.PNG)

Waiting for your review,

**Comment by deepika537** [comment]
Thank you so much. My issues got resolved
