### ISSUE TITLE
Store html content in database

### ISSUE THREAD

**Issue by deepika537** [salimk/Rcrawler#14]
how can I save the downloaded html with Rcrawler to a database instead of saving it to the local folder.

**Comment by salimk** [comment]
You can save collected HTML files into database table either by using Shell  or R SQL interface
## Shell  
```
for f in /path/to/files/folder/*.txt
do
    mysql -e "LOAD DATA INFILE '"$f"' INTO TABLE [tablename] FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES" -u [username] --password= [password] [databasename]
echo "Done: '"$f"' at $(date)"
done
```
## Using R, 
1- establishing a connection between R and your RDBMSs see the link bellow for more details  https://cran.r-project.org/doc/manuals/r-devel/R-data.html#R-interface-packages 
2- Load HTML files into R variable with LoadHTMLFiles() function (Rcrawler)
3- Finally, follow your R SQL interface manual to do an insert into query from R variable directly to your Database .
