### ISSUE TITLE
Keywords, can they be some form of regex or pattern search? Esp in the case of inflected words?

### ISSUE THREAD

**Issue by jacekkotowski** [salimk/Rcrawler#19]
I am trying to crawl Polish websites. Here the word can have several inflection endings, it may also exist with slight change of the root of word. Can one use a "keyword" options with wildcards or basic regex? Can boolean logic be used?
I am very grateful for your very useful plugin and I wish you lots of success!!!

**Comment by salimk** [comment]
yes you can pas regex in a keyword argument, in fact, Rcrawler perform a  gregexpr check then count the number of occurrences 

`  m<-sum(gregexpr(keyword ,text, fixed=TRUE,ignore.case = TRUE)[[1]] > 0)`

**Comment by salimk** [comment]
With the vesrion 0.1.9 (Just released)  you can also crawl a website search results ,
Subscribe to our mailing list to receive last updates http://eepurl.com/dMv_7s
