### ISSUE TITLE
I can't ignore URL parameters joined by ";"

### ISSUE THREAD

**Issue by andresrcs** [salimk/Rcrawler#20]
When I execute this code
```r
Rcrawler("http://www.tirodefensivoperu.com/forum/", 4, 4,
         urlregexfilter = "?topic",
         ExtractXpathPat = c("//*[(@id = 'top_subject')]", "//div[@class='inner']"),
         PatternsNames = c("title", "post"),
         ManyPerPattern = TRUE,
         ignoreUrlParams = c("PHPSESSID", "prev_next")
         )
```
I still get scraped this type of urls

https://www.tirodefensivoperu.com/forum/index.php?topic=11796.0;prev_next=prev

Is there a way to specify the joining character?

**Comment by salimk** [comment]
In general, ";" it's not used in URLs. But since it's included the RFC we have added it in our program.
```R
> Linkparamsfilter(URL = "https://www.tirodefensivoperu.com/forum/index.php?topic=11796.0&prev_next=prev","prev_next")
[1] "https://www.tirodefensivoperu.com/forum/index.php?topic=11796.0"
```
This update will be included the next release,

**Comment by salimk** [comment]
Subscribe to our mailing list to receive last updates http://eepurl.com/dMv_7s
