### ISSUE TITLE
Can Recrawler be used to scrape/crawl bilingual sites based on CSS selectors or Xpath?

### ISSUE THREAD

**Issue by mzeidhassan** [salimk/Rcrawler#21]
Hi Recrawler team,

I am new to R and Recrawler. I would like to know if Recrawler can be used to scrape/crawl bilingual sites, let's say I have this English site: 
https://government.ae/en
and this is the corresponding Arabic one:
https://government.ae/ar-ae

How can I use Recrawler to get the bitext from them and save the output in tab-delimited file?
Can you crawl only texts based on div tag, CSS selectors or maybe xpath?

Thanks

**Comment by salimk** [comment]
Yes you just have to set appropriate  Sys.locale 

For Arabic : 
` Sys.setlocale("LC_ALL","Arabic") `
In this example we fetch extract titles 
`Rcrawler(Website = "https://government.ae/",no_cores = 4,no_conn = 4, ExtractXpathPat = "//*/h2")`

![rcrawlerea](https://user-images.githubusercontent.com/17308124/48445739-34faee80-e78f-11e8-88c5-af80caec3080.JPG)

**Comment by salimk** [comment]
Rcrawler v0.1.9 is just released with a lot of features , 
Subscribe to our mailing list to receive last updates http://eepurl.com/dMv_7s
