### ISSUE TITLE
Arabic characters are not rendered correctly

### ISSUE THREAD

**Issue by mzeidhassan** [salimk/Rcrawler#22]
Hi Salim,

I was testing Rcrawler with 'http://www.emiratesmarsmission.ae/ar//' and I found out that all Arabic characters in the saved HTML files are turned into unicode. 

Here is an example:

> 
 <U+0628><U+0639><U+062F><U+0627><U+0644><U+0627><U+0646><U+062A><U+0647><U+0627><U+0621><U+0645><U+0646><U+0639><U+0645><U+0644><U+064A><U+0629><U+062A><U+0635><U+0646><U+064A><U+0639><U+0623><U+062F><U+0648><U+0627><U+062A><U+0627><U+0644><U+0645><U+062C><U+0633><U+0645><U+0627><U+0644><U+0647><U+0646><U+062F><U+0633><U+064A><U+0644><U+0644><U+0642><U+0645><U+0631><U+0627><U+0644><U+0627><U+0635><U+0637><U+0646><U+0627><U+0639><U+064A><U+064A><U+0642><U+0648><U+0645><U+0645><U+0647><U+0646><U+062F><U+0633><U+0636><U+0645><U+0627><U+0646><U+0627><U+0644><U+062C><U+0648><U+062F><U+0629><U+0628><U+0645><U+0639><U+0627><U+064A><U+0646><U+0629><U+0627><U+0644><U+0623><U+062F><U+0648><U+0627><U+062A><U+0627><U+0644><U+062A><U+064A><U+062A><U+0645><U+062A><U+0635><U+0646><U+064A><U+0639><U+0647><U+0627> <U+064A><U+0642><U+0648><U+0645><U+0645><U+0647><U+0646><U+062F><U+0633><U+0627><U+0644><U+0645><U+0631><U+0643><U+0632><U+0628><U+062A><U+0635><U+0646><U+064A><U+0639><U+0623><U+062F><U+0648><U+0627><U+062A><U+0627><U+0644><U+0645><U+062C><U+0633><U+0645><U+0627><U+0644><U+0647><U+0646><U+062F><U+0633><U+064A><U+0644><U+0644><U+0642><U+0645><U+0631><U+0627><U+0644><U+0627><U+0635><U+0637><U+0646><U+0627><U+0639><U+064A>

Any idea how to fix this and make the Arabic text rendered normally?

Thanks,
Mohamed Zeid

**Comment by mzeidhassan** [comment]
If I use this `list(DATA, localeToCharset('UTF-8'))`, the Arabic text is rendered correctly in R Studio, but still the crawled HTML files are showing unicode characters. Any idea how to save the crawled HTML files in regular Arabic text?

**Comment by Rifakh** [comment]
Hi, 

Sys.setlocale("LC_ALL","Arabic")

works for me.

**Comment by salimk** [comment]
We have fixed the issue now encoding will reflect on saved HTML files, but before start crawling you need to run :
`Sys.setlocale("LC_CTYPE","Arabic_Saudi Arabia.1256")`

![capturewritefilearabic](https://user-images.githubusercontent.com/17308124/47234500-fcedcf00-d3cd-11e8-8a1d-edcbe40ea9bc.JPG)
Update will be released in the next few days you will be notified

**Comment by salimk** [comment]
update version 0.1.9 is released, enjoy!
subscribe to our mailing list to stay updated http://eepurl.com/dMv_7s

**Comment by mohammedyahiaibrahim** [comment]
thanks so much.
