### ISSUE TITLE
problem with ampersand

### ISSUE THREAD

**Issue by mmooney512** [salimk/Rcrawler#26]
When running following code
```{r} 
Rcrawler(Website = crawl_page
, no_cores = 2
, no_conn = 2
, RequestsDelay = 1
, MaxDepth = 3
, DIR = 'https://www.indeed.com/jobs?q=senior+data+analyst&l=Tampa%2C+FL&sort=date'
, urlregexfilter = c("/rc/","start="))
```

There is an issue when there is an ampersand in the web address returned to the Data INDEX.  
It is getting converted to &amp;
instead of the real & sign.
so in the INDEX it will show as 
https://www.indeed.com/jobs?q=senior+data+analyst&amp;l=Tampa%2C+FL&amp;sort=date&amp;start=40

Instead of 
https://www.indeed.com/jobs?q=senior+data+analyst&l=Tampa%2C+FL&sort=date&start=40

So in effect the parameters:
l, sort, and start are not being passed the correct values in the URL. 
Let me know if you need any more info to help correct. 
Thanks
--Michael

**Comment by salimk** [comment]
we have added some facilities to crawl/scrape search result, you will be notified when the package is released.
`Rcrawler(Website = "https://www.indeed.com/jobs?q=senior+data+analyst&l=Tampa,+FL&sort=date"
         , no_cores = 4
         , no_conn = 4
         , crawlUrlfilter = c("/rc/","start="),dataUrlfilter = "/rc/")`
   subscribe to our mailing list to stay updated  http://eepurl.com/dMv_7s

**Comment by salimk** [comment]
Update v 0.1.9 is released enjoy
For more precision : 
`
Rcrawler(Website = "https://www.indeed.com/jobs?q=data+analyst&l=Tampa,+FL", no_cores = 4 , no_conn = 4,  crawlUrlfilter = c("/rc/","start="), dataUrlfilter = "/rc/",  crawlZoneCSSPat = "td#resultsCol"   
         )
`
