### ISSUE TITLE
LinkExtractor gives empty result.

### ISSUE THREAD

**Issue by slfan2013** [salimk/Rcrawler#28]
The following code gives empty result. 
`pageinfo<-LinkExtractor("https://www.michaelkors.com/blakely-leather-satchel/_/R-US_30S8SZLM6L")`
The result is 
```
[[1]]
[[1]][[1]]
[1] 748

[[1]][[2]]
[1] "https://www.michaelkors.com/blakely-leather-satchel/_/R-US_30S8SZLM6L"

[[1]][[3]]
[1] "NULL"

[[1]][[4]]
[1] 628

[[1]][[5]]
[1] ""

[[1]][[6]]
[1] ""

[[1]][[7]]
[1] ""

[[1]][[8]]
[1] ""

[[1]][[9]]
[1] ""


[[2]]
logical(0)
```

**Comment by salimk** [comment]
the website server require Origin field in HTTP header request: 
you can fix the issue instantly by doing the following steps : 
` edit(LinkExtractor)
`
Locate line n° 22 and replace it with : 
`    page<-tryCatch(httr::GET(url, httr::user_agent(Useragent),httr::timeout(Timeout), httr::add_headers(`Origin`=base,`:authority:`=base)) , error=function(e) NULL)
`

**Comment by salimk** [comment]
Update v 0.1.9 is released with this issue fixed 
Subscribe to our mailing list to receive last updates http://eepurl.com/dMv_7s
