### ISSUE TITLE
Password Protected Site

### ISSUE THREAD

**Issue by kammywwak** [salimk/Rcrawler#3]
Is it possible to use RCrawler on a password protected site?

**Comment by salimk** [comment]
what did you mean by password protected website ;  websites with authentification like forums, or websites with directory password protection ?

**Comment by SixiangHu** [comment]
got the same questions that if the web contents can be seen after authentification (username and pwd, which are know), will Rcrawler have some functionality to act "login" action automatically?

**Comment by 00raymond00** [comment]
I'm also trying to use Rcrawler to scrape content from a forum that you can only access after logging in with a username/password.

**Comment by tdalis** [comment]
I don't see anyone replying here, is there another way we can automatically crawl sites with R? Is RSelenium a good choice?

**Comment by salimk** [comment]
hello guys, @kammywwak @SixiangHu  @SixiangHu @tdalis @00raymond00 
we have released Rcrawler v0.1.9 , now you could crawl/ parse password protected website using phantomjs web driver : 
 
`install_browser()`
`br<-run_browser()`
#### logged-in session
`  br<-LoginSession(Browser = br, LoginURL = 'http://glofile.com/wp-login.php',`
`                   LoginCredentials = c('demo','rc@pass@r'),`
`                   cssLoginFields =c('#user_login', '#user_pass'),`
`                  cssLoginButton='#wp-submit' )`
#### Retreive a private webpage 
`page<-LinkExtractor(url = ,Browser =br )`
#### Then scrape specific pages 
`data<-ContentScraper(Url = , browser =br )`  
#### Or Crawl the website (slow) 
`Rcrawler(Website = ,no_conn =1 ,no_cores =1 ,LoggedSession = )`

Subscibe to our mailing-list to receive last Rcrawler updates  http://eepurl.com/dMv_7s
