### ISSUE TITLE
Rcrawler does not return any results

### ISSUE THREAD

**Issue by anupnyk** [salimk/Rcrawler#31]
I ran the code for Rcrawler using the sample example, however this did not return any results.

can someone let me know what I am missing?

crawler(Website = "http://www.glofile.com", no_cores = 4, no_conn = 4)
In process : 1..
Progress: 100.00 %  :  1  parssed from  1  | Collected pages: 0  | Level: 1 
+ Check INDEX dataframe variable to see crawling details 
+ Collected web pages are stored in Project folder 
+ Project folder name : glofile.com-050550

**Comment by tmerrittsmith** [comment]
I had this issue, and found that loading ```library(httr)``` first fixed things.

(Presuming your code above is ```Rcrawler(Website...```

**Comment by salimk** [comment]
We have fixed the issue, 

Subscribe to our mailing list to stay updated  http://eepurl.com/dMv_7s 

Thanks
