### ISSUE TITLE
bypass or initiate javascript loaded menus

### ISSUE THREAD

**Issue by stevemings** [salimk/Rcrawler#32]
Thank you so much for putting this together!  
I would like to scrape a page that has a menu of categories, but the crawler stops at the "show all" or "show more" buttons that load the remaining content of the menu. Is there a workaround solution to this?

**Comment by salimk** [comment]
The current R version 0.1.8 is based on GET request which is unable to render javascript dynamic elements. Actually, we are working to extend the fetching process by implementing a web driver (virtual browser) within Rcrawler. You will be notified when released soon.

**Comment by stevemings** [comment]
Thank you!

**Comment by salimk** [comment]
Hello @stevemings 
Good news, 0.1.9 is released, with web driver integration, which means you can parse javascript rendered pages . 
`install_browser()`
`br<-run_browser()
`
check the manual for more detail

**Comment by stevemings** [comment]
Thank you immensely!
