### ISSUE TITLE
Latest version has only "ExtractPatterns" argument instead of "ExtractXpathPat" and "ExtractCSSPat"

### ISSUE THREAD

**Issue by hermandr** [salimk/Rcrawler#33]
Hi,

The latest version does not sync with the ReadMe page.
Several references to Xpath and CSS patterns which does not exist now in the code.

In Rcrawler only "ExtractPatterns" is a valid argument.
In ContentScraper only "patterns" is a valid argument.
No CSS patterns allowed anymore.

May be the ReadMe page should be updated.

Regards,
Herman

**Comment by salimk** [comment]
Hello, 
we recommend installing Rcrawler CRAN ,
`>install.packages("Rcrawler")
 >library(Rcrawler)
`
Source code on GitHub is unstable. we will update it as soon as possible.
For now, the stable source code is available on cran here: https://cran.r-project.org/src/contrib/Rcrawler_0.1.8-0.tar.gz

**Comment by salimk** [comment]
github updated to latest version 0.1.9

Subscribe to our mailing list to receive last updates http://eepurl.com/dMv_7s
