### ISSUE TITLE
Rcrawler only returning one HTML file for entire website

### ISSUE THREAD

**Issue by timothyjgraham** [salimk/Rcrawler#4]
Hi there,

I tried to crawl https://www.gov.sg/ using Rcrawler, however it only returns one HTML page in the local directory (and one row in the INDEX object).

Can you please let me know what is going wrong here?

Many thanks,

Tim

**Comment by daswesen** [comment]
I have the same problem, looks like there are issues with https.

**Comment by salimk** [comment]
good news the next release of Rcrawler support https, we are working on it,
it will be available on cran as soon as possible (5 days).

2017-10-04 10:25 GMT+01:00 daswesen <notifications@github.com>:

**Comment by salimk** [comment]
we invite you to try the last release or Rcrawler v 0.1.3 (just uploaded on cran, so its available as Package source)
    -support https website
    -support scraping a website by search term (keywords matching)
    -less error during crawling process
