### ISSUE TITLE
Possible features: "stop when found" function and "ignore all parameters"

### ISSUE THREAD

**Issue by WHardyPL** [salimk/Rcrawler#41]
Hello! I love the package! Extremely powerful!

I thought about two possible features that could come in handy while reading about the current functions:

1) I think it would be nice to implement a "stop" procedure so that the crawler does not continue once a certain target (or a certain number of targets?) is found. 

For example, I might want to scrape a set of websites with unknown structures, knowing that each of them has a specific .pdf file somewhere. If I am only interested in these files from each of the websites, it would be much faster for me if I could tell the robot to stop searching a particular website once it finds the file.

2) would it be possible to just omit all the parameters and not the ones specifically specified? the algorithm could check for any word between "?" and "=" or between "&" and "=" or am I missing something?

Thanks and best!

**Comment by salimk** [comment]
we have added IgnoreAllUrlParams argument inside the Rcrawler function, we are studying the break's implementation.
  subscribe to our mailing list to stay updated  http://eepurl.com/dMv_7s
