### ISSUE TITLE
why does Rcrawler have trouble with this page?

### ISSUE THREAD

**Issue by rcorty** [salimk/Rcrawler#44]
Rcrawler doesn't find the links in the filterable grid here:

https://www.crowdpac.com/campaigns

When I run:

```
Rcrawler(Website = 'https://www.crowdpac.com/campaigns',
		 no_cores = 4, 
		 no_conn = 4)
```
It only crawls 5 pages -- the pages linked in the top and bottom banners.

**Comment by salimk** [comment]
Hello , 
Rcrawler use GET request which can't render Javascript sections, the solution is to use a web driver like selenium to simulate a real browser. Actually, we are working to implement this feature inside our package. It will be available in the next few days. You will be notified when it's available on cran.

**Comment by salimk** [comment]
update version 0.1.9 is released, enjoy!
subscribe to our mailing list to stay updated http://eepurl.com/dMv_7s
