### ISSUE TITLE
How to Not store/save html pages downloaded with Rcrawler

### ISSUE THREAD

**Issue by athammad** [salimk/Rcrawler#46]
Wonderful package Salim!!!

I would like to know how I can avoid storing the html pages of the websites that I am crawling. I just need the list of urls for each website that are already available in the INDEX data.frame. 
Is there an option to do it?

Thank you :)

**Comment by salimk** [comment]
The next release will include the option ` saveOnDisk=TRUE`  to avoid storing collected data on files.
Thank you

**Comment by salimk** [comment]
update version 0.1.9 is released, enjoy!
subscribe to our mailing list to stay updated http://eepurl.com/dMv_7s
