### ISSUE TITLE
Retreive all hyperlinks

### ISSUE THREAD

**Issue by Close-your-eyes** [salimk/Rcrawler#47]
Thank you for the convenient package to crawl web page data.
I was especially interested in getting hrefs from a web site. In the readme.md I found that it is possible to pass an argument, "ExtractPatterns= c("//*/a/@href")",  in the Rcrawler-function which should do the job.
Unfortunately though, this argument has been removed?!

I am usually not the impatient type, but could you tell me what would be the easiest way to get all hrefs from a web page under the current Rcrawler version? Using the LinkExtractor, for instance, does not do it by default.

Thanks for the support!

**Comment by salimk** [comment]
- Retrieve all links from a one or multiple specific pages
```
links<-ContentScraper(Url = "http://glofile.com/2017/06/08/placements-quelles-solutions-pour-doper/", 
                                      XpathPatterns = "//*/a/@href" ,
                                       ManyPerPattern = TRUE)
```


- Retrieve all links from the whole website 
```
Rcrawler( Website = "http://glofile.com/", 
                 ExtractXpathPat = "//*/a/@href",
                 ManyPerPattern = TRUE)`
```
