### ISSUE TITLE
Error when crawling

### ISSUE THREAD

**Issue by timothyjgraham** [salimk/Rcrawler#5]
When I try to crawl the following website, it always returns an error when the crawler gets to 24.98% complete.

Here is the R command:

`Rcrawler(Website = "http://www.lamoncloa.gob.es", no_cores = 1, no_conn = 1)`

Here is the error:

```
24.98 %  :  582  parssed from  2330 
In process : 586 ..
Error in allpaquet[[s]][[1]][[3]] : subscript out of bounds
```

Thanks,

Tim

**Comment by salimk** [comment]
the issue has been resolved , you can try the next release of Rcrawler in the coming days

**Comment by timothyjgraham** [comment]
I look forward to it!

**Comment by timothyjgraham** [comment]
@salimk Any update on the new release? Thanks!

**Comment by salimk** [comment]
Yes we have released version 0.1.2, hte issue is fixed.

**Comment by timothyjgraham** [comment]
Oh, thanks for letting me know. I was checking GitHub but I realise it is updated on CRAN. Thanks again.

**Comment by mochtak** [comment]
@salimk I see the thread is closed now but I have encountered the same problem with the new release.

Here is the R command:
`crawl_1 <- Rcrawler(Website="http://www.hdz.hr/")`

Here is the error:
`In process : 9449 ..9450 ..9451 ..
53.36 %  :  9449  parssed from  17709 
In process : 9452 ..
Error in allpaquet[[s]][[1]][[3]] : subscript out of bounds
In addition: Warning message:
'xml_find_one' is deprecated.
Use 'xml_find_first' instead.
See help("Deprecated") `

Thanks.

Michal

**Comment by salimk** [comment]
we invite you to try the last release or Rcrawler v 0.1.3
- support of https website 
- scraping a website by search term (keywords matching)
- subscript out of bounds error my result from different situations,  we believe we overcome almost of them in this release.

**Comment by daswesen** [comment]
How do we get the new version? CRAN has v 0.1.2 still... dev version in R pulls v 0.1

**Comment by salimk** [comment]
As you can see we have just uploaded the source package on cran , cran should build binary version automatically soon (24 hour),  
![capture](https://user-images.githubusercontent.com/17308124/31497717-cdf060b4-af57-11e7-9462-068cf347612e.PNG)
However, you can compile and install the package source on your computer  using 
install.packages("Rcrawler", type = "source" )

**Comment by daswesen** [comment]
Ah, wasn't there a few minutes ago. install.packages("Rcrawler", type = "source" ) gives me 0.1.2 though. You see, we cannot wait to get hold of the new version ;-) Thanks for your efforts!

**Comment by taby0** [comment]
Thanks! I will test it during the weekend!
