### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by Asabuzz** [salimk/Rcrawler#7]
Hello, 

I'm new user of R and R Studio and i'm very interesting by your web crawler. Thanks for it.

But i have a problem when i want to install the package.

```
> system("java -version")
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

Downloading GitHub repo salimk/Rcrawler@master
from URL https://api.github.com/repos/salimk/Rcrawler/zipball/master
Installing Rcrawler
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/jz/3njpl5xx15zc_xrsgpn53z_00000gn/T/Rtmpz4mtT1/devtools38c076f3b618/salimk-Rcrawler-fb92537'  \
  --library='/Users/damiencosta/Library/R/3.4/library' --install-tests 

* installing *source* package ‘Rcrawler’ ...
** R
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: impossible de charger l'objet partagé '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
ERROR: lazy loading failed for package ‘Rcrawler’
* removing ‘/Users/damiencosta/Library/R/3.4/library/Rcrawler’
Installation failed: Command failed (1)
```

Someone for help please ?

**Comment by salimk** [comment]
Did you try
 install.packages("Rcrawler", INSTALL_opts = "--no-multiarch")

**Comment by Asabuzz** [comment]
Yes, the package installs, but after when i try to run it, this message appears 

```
> library(Rcrawler)
Erreur : package or namespace load failed for ‘Rcrawler’:
 .onLoad a échoué dans loadNamespace() pour 'rJava', détails :
  appel : dyn.load(file, DLLpath = DLLpath, ...)
  erreur : impossible de charger l'objet partagé '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
```

**Comment by salimk** [comment]
a similar issue was resolved through this https://stackoverflow.com/questions/30738974/rjava-load-error-in-rstudio-r-after-upgrading-to-osx-yosemite 
this issue is related to rjava package which our package import to be used in a minor function . in the next release of rcrawler this particualr function we will be omitted .

**Comment by echoesinthestairwell** [comment]
what worked for me was to upgrade to the latest java version (1.8.0_131-b11) *via homebrew* (and to upgrade to the latest rstudio release). and then to run the following commands via the terminal:

install_name_tool -add_rpath /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/H‌​ome/jre/lib/server /usr/local/lib/R/3.4/site-library/rJava/libs/rJava.so

and

sudo ln -s $(/usr/libexec/java_home)/jre/lib/server/libjvm.dylib /usr/local/lib

best,
mahmood

**Comment by Asabuzz** [comment]
Finaly, what worked for me was to downgrade rJava from 0.9.9 to 0.9.7 using source package from Rforge (https://www.rforge.net/rJava/files/).

**Comment by salimk** [comment]
the rjava  function will be omitted in the next release, thank you for your time
