### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by MartinsRodrigo** [salimk/Rcrawler#8]
Is it possible to get attributes using ContentScraper(), like I would get using rvest with the following commands?

read_html(url) %>% 
                    html_nodes(xpath) %>%
                    html_attr("href")

**Comment by salimk** [comment]
Using Xpath you can call attribute value. For example the two follwing command scrape all href value in this web page 

1. First download the page, 
`pageinfo<-LinkExtractor("http://glofile.com/index.php/2017/06/08/athletisme-m-a-rome/")
`
2. Then  this expression "//*/a/@href" find all href value of <a> tags  /a/@href wherever located on the page //*
`Data<-ContentScraper(pageinfo[[1]][[10]],c("//*/a/@href"), ManyPerPattern = TRUE)
`
